<Project>
  <PropertyGroup>
    <AsukaVersion>0.1.0.1</AsukaVersion>
    <Version>$(AsukaVersion)</Version>
    <AssemblyVersion>$(AsukaVersion)</AssemblyVersion>
    <FileVersion>$(AsukaVersion)</FileVersion>
    <InformationalVersion>$(AsukaVersion)</InformationalVersion>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <LangVersion>latest</LangVersion>
    <Platforms>x64;ARM64</Platforms>
    <Platform Condition="'$(Platform)' == '' Or '$(Platform)' == 'AnyCPU' Or '$(Platform)' == 'Any CPU'">x64</Platform>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\artifacts\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
