<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Matcha.Protocols</RootNamespace>
    <AssemblyName>Matcha.Protocols</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Matcha.Core/Matcha.Core.csproj" />
  </ItemGroup>
</Project>
