<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
    <RootNamespace>Asuka.App</RootNamespace>
    <AssemblyName>Asuka</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <AppxPackageDir>$(MSBuildProjectDirectory)\..\..\artifacts\msix\</AppxPackageDir>
    <Platforms>x64;ARM64</Platforms>
    <Platform Condition="'$(Platform)' == '' Or '$(Platform)' == 'AnyCPU' Or '$(Platform)' == 'Any CPU'">x64</Platform>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">false</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationIcon>Assets\Asuka.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Asuka.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Showcase\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Asuka.Core/Asuka.Core.csproj" />
    <ProjectReference Include="../Asuka.Protocols/Asuka.Protocols.csproj" />
  </ItemGroup>
</Project>
