<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Asuka.Protocols</RootNamespace>
    <AssemblyName>Asuka.Protocols</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Asuka.Core/Asuka.Core.csproj" />
  </ItemGroup>
</Project>
